---

- name: check out the repo
  ansible.builtin.git:
    repo: "https://github.com/wasya-co/docker_drupal.git"
    dest: "/opt/projects/docker_drupal"
    version: "0.0.0"

- ansible.builtin.file:
    path: "/opt/projects/docker_drupal/volumes/{{ appliance_slug }}/web/sites/default/files/config_{{ appliance_slug }}/sync"
    state: directory
    recurse: yes

- name: docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml
    dest: /opt/projects/docker_drupal/docker-compose.yml

- name: settings.php
  ansible.builtin.template:
    src: settings.php
    dest: /opt/projects/docker_drupal/volumes/piousbox_com/web/sites/default/settings.php

- ansible.builtin.command: docker compose up -d
  args:
    chdir: /opt/projects/docker_drupal

- ansible.builtin.command: "docker exec {{ appliance_slug }} composer install"
  args:
    chdir: /opt/projects/docker_drupal
