
services:

  app:
    container_name: {{ appliance_slug }}
    image: piousbox/php83:0.0.2
    volumes:
      - app_data:/var/www/html
      - type: bind
        source: root/_bashrc
        target: /root/.bashrc
      - type: bind
        source: ./etc/apache2/sites-available/000-default-drupal.conf
        target: /etc/apache2/sites-available/000-default.conf
      - type: bind
        source: composer.json
        target: /var/www/html/composer.json
      - type: bind
        source: composer.lock
        target: /var/www/html/composer.lock
      - type: bind
        source: sites
        target: /var/www/html/web/sites
    ports:
      - {{ app_port }}:80
    restart: 'unless-stopped'


  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    command:
      - '--default-authentication-plugin=mysql_native_password'
      - '--skip-log-bin'
    # container_name: mysql
    restart: 'unless-stopped'
    ports:
      - "{{ mysql_host_port }}:3306"
    environment:
      MYSQL_DATABASE: "{{ mysql_db }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_USER: "{{ mysql_user }}"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  app_data:
  mysql_data:

